// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpip76f6DmvQBQfi6EjkmLsAeIJrkU3Ew',
    appId: '1:510431822627:web:0459fe15b9eca493aa0296',
    messagingSenderId: '510431822627',
    projectId: 'flutter-chat-752e8',
    authDomain: 'flutter-chat-752e8.firebaseapp.com',
    storageBucket: 'flutter-chat-752e8.appspot.com',
    measurementId: 'G-FZJEVF6CWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6cp9Y8UH3mks4HYgxh3xMV_Tb_xZHVw',
    appId: '1:510431822627:android:59b095b548f45728aa0296',
    messagingSenderId: '510431822627',
    projectId: 'flutter-chat-752e8',
    storageBucket: 'flutter-chat-752e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPiH3QIGjlX2JxLahJRHb9PTbrQBfor8c',
    appId: '1:510431822627:ios:e6dd0f37230e47dfaa0296',
    messagingSenderId: '510431822627',
    projectId: 'flutter-chat-752e8',
    storageBucket: 'flutter-chat-752e8.appspot.com',
    iosClientId: '510431822627-25h0olv2l6bikbvsafm5riro37nj8et3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPiH3QIGjlX2JxLahJRHb9PTbrQBfor8c',
    appId: '1:510431822627:ios:e6dd0f37230e47dfaa0296',
    messagingSenderId: '510431822627',
    projectId: 'flutter-chat-752e8',
    storageBucket: 'flutter-chat-752e8.appspot.com',
    iosClientId: '510431822627-25h0olv2l6bikbvsafm5riro37nj8et3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );
}
